/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#fef8f6",
        "surface-container-low": "#f8f2f1",
        "on-primary-container": "#988a82",
        "on-surface": "#1d1b1b",
        "surface": "#fef8f6",
        "surface-tint": "#685c55",
        "on-surface-variant": "#4e4540",
        "secondary": "#506354",
        "outline-variant": "#d1c4bd",
        "surface-container-high": "#ece7e5",
        "secondary-fixed": "#d3e8d5",
        "on-secondary-fixed": "#0e1f13",
        "on-error-container": "#93000a",
        "on-secondary-container": "#546758",
        "primary": "#170f0a",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#4f453e",
        "secondary-fixed-dim": "#b7ccb9",
        "primary-fixed-dim": "#d3c3ba",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#d3c3ba",
        "outline": "#7f756f",
        "tertiary-fixed": "#ffdbd0",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#3a0b00",
        "primary-container": "#2d241e",
        "surface-dim": "#ded9d7",
        "surface-container-highest": "#e7e1e0",
        "primary-fixed": "#f0dfd6",
        "tertiary-container": "#481504",
        "surface-bright": "#fef8f6",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary": "#280500",
        "inverse-surface": "#32302f",
        "on-primary-fixed": "#221a14",
        "surface-variant": "#e7e1e0",
        "on-tertiary-fixed-variant": "#733521",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#394b3d",
        "on-background": "#1d1b1b",
        "on-tertiary-container": "#c87860",
        "tertiary-fixed-dim": "#ffb59e",
        "on-tertiary": "#ffffff",
        "surface-container": "#f2edeb",
        "inverse-on-surface": "#f5f0ee",
        "secondary-container": "#d0e5d2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "xl": "80px",
        "md": "24px",
        "container-max": "1200px",
        "sm": "12px",
        "gutter": "24px",
        "base": "8px",
        "lg": "48px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
